version: '3.8'
services:
  postgres:
    image: postgres:latest
    container_name: your
    environment:
      POSTGRES_USER: your
      POSTGRES_PASSWORD: your
      POSTGRES_DB: your
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    restart: unless-stopped

  pgadmin:
    image: dpage/pgadmin4:latest
    container_name: your
    environment:
      PGADMIN_DEFAULT_EMAIL: your
      PGADMIN_DEFAULT_PASSWORD: your
    ports:
      - "5050:80"
    depends_on:
      - postgres
    restart: unless-stopped

volumes:
  postgres_data:

